compressionLevel: mixed

enableColors: false

enableGlobalCache: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0076
    level: discard

nodeLinker: pnp

npmPublishAccess: public

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  vite@*:
    dependencies:
      supports-color: "*"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.7.0.cjs
